### PR TITLE
fix: prevent automatic ingestion of all notes for non-followed actors

### LINKED ISSUE #15: Ingesting All Notes When Visiting New Actor
When visiting a new actor profile, the reader is currently ingesting all notes associated with that actor, even if the user is not following them.

- Right now, we cache all notes we view in the DB, that's why they get ingested. We can skip that when loading an outbox and rely on regular http caching.

### PR DESCRIPTION
**Pull request by akhileshthite**
closes #15 

`forceIngest` did the trick.

### CODE REVIEW

**Review by RangerMauve — CHANGES_REQUESTED** [review]
Instead of doing it inside `ingestNote` could you skip invoking `ingestNote` in places it's not needed? Like inside `ingestActivty` where you can check that the note is the same actor as the activity? It'll be a lot of overhead to do an extra database call for every note.

File: db.js [hunk 1]
```diff
@@ -371,6 +376,12 @@ export class ActivityPubDB extends EventTarget {
   }
 
   async ingestNote (note) {
+    const isFollowed = await this.isActorFollowed(note.attributedTo)
```
Comment (RangerMauve) [inline db.js]: Does it work when you remove this check now?

**Review by RangerMauve — CHANGES_REQUESTED** [review]

File: db.js (hunk 1 above)
Comment (akhileshthite) [reply db.js]: Uh ohh.
Not working, it's still ingesting the notes if I remove `isFollowed`.

Comment (RangerMauve) [reply db.js]: Set breakpoints inside `ingestNote` and see what it's parent is in the call stack. It might be getting invoked from a different place. Also check that it isn't being invoked from the `ingestActivty` call. If it is, check that our attributedTo check is working correctly by setting a breakpoint and checking the values make sense.

Comment (akhileshthite) [reply db.js]: Yeah it's `getNote`

Comment (RangerMauve) [reply db.js]: Maybe `getNote` just shouldn't be ingesting notes then?

I think we had that in there initially because we wanted to cache notes. We can remove it and leave the caching to the browser and only ingest notes from ingested collections.

Comment (akhileshthite) [reply db.js]: did this:
https://github.com/hyphacoop/reader.distributed.press/pull/21/commits/fce66f0c2844f7c98af83e4e4864cf9a5c83c8f5

we're using `getNote` in `post.js`

**Review by RangerMauve — APPROVED** [review]
Excellent! Feel free to merge.
